### ISSUE TITLE
Implement MOH 710 report

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-kip#1]
The MOH 710 report in Kenya is a monthly report that aggregates child health service indicators, including immunization. For KIP, the user will also be able to select a custom date range for the report (in addition to the default calendar months). The mockup is below.

- [x] The MOH 710 report can be accessed from the side menu of the KIP app (similar to HIA2 reports in ZEIR app). See icon below.
  <img src="https://user-images.githubusercontent.com/3488986/29468817-b1be1b7e-843d-11e7-974f-418b46063a04.png" width="256">
- [x] Tapping on the MOH 710 icon in the side menu opens the below screen.
  <img src="https://user-images.githubusercontent.com/3488986/29468926-1b5b8be8-843e-11e7-9d3f-3570122117d3.png" width="500">
- [x] Instead of "KIP Reports" at the top, it should say "MOH 710"
- [x] Instead of "Report date", it should say "Report month"
- [x] The Report date/month dropdown shows a dropdown of all available calendar month reports, with most recent calendar month listed on top.
- [x] The custom date range button opens a date dialog where the user can select a custom start and end date for the report. See first image below. Tapping outside the dialog also cancels the interaction. To clear the dates, a button is added to clear the dates. If there is a custom data range entered and the user clicks the date range, the user may adjust the numbers without cancelling out. See @rowo for questions or concerns.
  - <img src="https://user-images.githubusercontent.com/1584163/29636847-2d2635c2-8820-11e7-899d-e1868fe46923.png" width="500">
  - <img src="https://user-images.githubusercontent.com/1584163/29636846-2d24f586-8820-11e7-81b1-77f01636df98.png" width="500">
- [x] Selecting a report calendar month or custom date range re-calculates the indicators to show only the values for that report calendar month or custom date range.
- [x] The list of antigens (i.e. vaccines) and other service indicatorsto show in the list and the age breakdowns can be found in the reporting template [here](https://docs.google.com/spreadsheets/d/164eDwF2ZvcfbiQa7Ox4LpgaeBdPn1U-dYu4ejBqjiV0/edit#gid=880186197). Some of the indicators cannot be calculated, so see comments in the spreadsheet. These should just be displayed as "N/A" in the app.

**Comment by cafootitt** [comment]
UI looks good to me.

@faith-mutua Next week, please borrow @keymane's tablet to test that the values are calculated correctly in the app. Make sure to test the report month filters too.

**Comment by faith-mutua** [comment]
@cagulas the values are calculated correctly and the month filters are working fine

**Comment by cafootitt** [comment]
This is done and released on Sept 20, 2017.
